#!/bin/bash

# To find out the required libs yourself, in bin dir: $ ldd cnc

cp bin/* appimage/appdir/usr/bin
cp lib/* appimage/appdir/usr/lib
cp rtlib/* appimage/appdir/usr/rtlib
cp include/* appimage/appdir/usr/include
cp vendor/icons/* appimage/appdir/usr/share/icons/hicolor
cp vendor/oce-upstream-V7_5_0beta/build/lin64/gcc/lib/* appimage/appdir/usr/lib
cp vendor/Clothoids/build/libClothoids_linux.so appimage/appdir/usr/lib
cp vendor/Clothoids//build/submodules/quarticRootsFlocke/libquarticRootsFlocke_linux.so appimage/appdir/usr/lib
cp vendor/Clothoids//build/submodules/Utils/libUtils_linux.so appimage/appdir/usr/lib

cp /lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libGL.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libGLdispatch.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libGLX.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libreadline.so.8 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libX11.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libfontconfig.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libfreeimage.so.3 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libfreetype.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libpng16.so.16 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libz.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libharfbuzz.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libmd4c.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libdouble-conversion.so.3 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libicui18n.so.72 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libicuuc.so.72 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libpcre2-16.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libzstd.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libglib-2.0.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libtinfo.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libxcb.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libexpat.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libjxrglue.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libjpeg.so.62 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libopenjp2.so.7 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libraw.so.20 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libtiff.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libwebpmux.so.3 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libwebp.so.7 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libOpenEXR-3_1.so.30 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libIex-3_1.so.30 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libImath-3_1.so.29 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libbrotlidec.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libgraphite2.so.3 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libicudata.so.72 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libpcre2-8.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libXau.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libXdmcp.so.6 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libjpegxr.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/liblcms2.so.2 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libgomp.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/liblzma.so.5 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libLerc.so.4 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libjbig.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libdeflate.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libIlmThread-3_1.so.30 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libbrotlicommon.so.1 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libbsd.so.0 appimage/appdir/usr/lib
cp /lib/x86_64-linux-gnu/libmd.so.0 appimage/appdir/usr/lib

cd appimage
./appimagetool-x86_64.AppImage appdir
